// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.6
// source: demomod.proto

package demomod

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demomod_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_demomod_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_demomod_proto_rawDescGZIP(), []int{0}
}

type Sum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Sum) Reset() {
	*x = Sum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demomod_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sum) ProtoMessage() {}

func (x *Sum) ProtoReflect() protoreflect.Message {
	mi := &file_demomod_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sum.ProtoReflect.Descriptor instead.
func (*Sum) Descriptor() ([]byte, []int) {
	return file_demomod_proto_rawDescGZIP(), []int{1}
}

type HelloResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *HelloResult) Reset() {
	*x = HelloResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demomod_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResult) ProtoMessage() {}

func (x *HelloResult) ProtoReflect() protoreflect.Message {
	mi := &file_demomod_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResult.ProtoReflect.Descriptor instead.
func (*HelloResult) Descriptor() ([]byte, []int) {
	return file_demomod_proto_rawDescGZIP(), []int{2}
}

func (x *HelloResult) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type EchoStream struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EchoStream) Reset() {
	*x = EchoStream{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demomod_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoStream) ProtoMessage() {}

func (x *EchoStream) ProtoReflect() protoreflect.Message {
	mi := &file_demomod_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoStream.ProtoReflect.Descriptor instead.
func (*EchoStream) Descriptor() ([]byte, []int) {
	return file_demomod_proto_rawDescGZIP(), []int{3}
}

type Sum_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	A int64 `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B int64 `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
}

func (x *Sum_Request) Reset() {
	*x = Sum_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demomod_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sum_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sum_Request) ProtoMessage() {}

func (x *Sum_Request) ProtoReflect() protoreflect.Message {
	mi := &file_demomod_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sum_Request.ProtoReflect.Descriptor instead.
func (*Sum_Request) Descriptor() ([]byte, []int) {
	return file_demomod_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Sum_Request) GetA() int64 {
	if x != nil {
		return x.A
	}
	return 0
}

func (x *Sum_Request) GetB() int64 {
	if x != nil {
		return x.B
	}
	return 0
}

type Sum_Result struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	C int64 `protobuf:"varint,1,opt,name=c,proto3" json:"c,omitempty"`
}

func (x *Sum_Result) Reset() {
	*x = Sum_Result{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demomod_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sum_Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sum_Result) ProtoMessage() {}

func (x *Sum_Result) ProtoReflect() protoreflect.Message {
	mi := &file_demomod_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sum_Result.ProtoReflect.Descriptor instead.
func (*Sum_Result) Descriptor() ([]byte, []int) {
	return file_demomod_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Sum_Result) GetC() int64 {
	if x != nil {
		return x.C
	}
	return 0
}

type EchoStream_Input struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *EchoStream_Input) Reset() {
	*x = EchoStream_Input{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demomod_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoStream_Input) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoStream_Input) ProtoMessage() {}

func (x *EchoStream_Input) ProtoReflect() protoreflect.Message {
	mi := &file_demomod_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoStream_Input.ProtoReflect.Descriptor instead.
func (*EchoStream_Input) Descriptor() ([]byte, []int) {
	return file_demomod_proto_rawDescGZIP(), []int{3, 0}
}

func (x *EchoStream_Input) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type EchoStream_Output struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Reply string `protobuf:"bytes,2,opt,name=reply,proto3" json:"reply,omitempty"`
}

func (x *EchoStream_Output) Reset() {
	*x = EchoStream_Output{}
	if protoimpl.UnsafeEnabled {
		mi := &file_demomod_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EchoStream_Output) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoStream_Output) ProtoMessage() {}

func (x *EchoStream_Output) ProtoReflect() protoreflect.Message {
	mi := &file_demomod_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoStream_Output.ProtoReflect.Descriptor instead.
func (*EchoStream_Output) Descriptor() ([]byte, []int) {
	return file_demomod_proto_rawDescGZIP(), []int{3, 1}
}

func (x *EchoStream_Output) GetReply() string {
	if x != nil {
		return x.Reply
	}
	return ""
}

var File_demomod_proto protoreflect.FileDescriptor

var file_demomod_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x64, 0x65, 0x6d, 0x6f, 0x6d, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x1e, 0x69, 0x6f, 0x2e, 0x6d, 0x6f, 0x75, 0x6c, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x6b, 0x69, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x22,
	0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x44, 0x0a, 0x03, 0x53, 0x75, 0x6d, 0x1a,
	0x25, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x61, 0x12, 0x0c, 0x0a, 0x01, 0x62, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x01, 0x62, 0x1a, 0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x0c, 0x0a, 0x01, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x01, 0x63, 0x22, 0x1f,
	0x0a, 0x0b, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22,
	0x49, 0x0a, 0x0a, 0x45, 0x63, 0x68, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x1a, 0x1b, 0x0a,
	0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x1a, 0x1e, 0x0a, 0x06, 0x4f, 0x75,
	0x74, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x72, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xc9, 0x02, 0x0a, 0x0a, 0x44,
	0x65, 0x6d, 0x6f, 0x6d, 0x6f, 0x64, 0x53, 0x76, 0x63, 0x12, 0x60, 0x0a, 0x03, 0x53, 0x75, 0x6d,
	0x12, 0x2b, 0x2e, 0x69, 0x6f, 0x2e, 0x6d, 0x6f, 0x75, 0x6c, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74,
	0x65, 0x72, 0x6b, 0x69, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x6d,
	0x6f, 0x2e, 0x53, 0x75, 0x6d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2a, 0x2e,
	0x69, 0x6f, 0x2e, 0x6d, 0x6f, 0x75, 0x6c, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x6b,
	0x69, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x53,
	0x75, 0x6d, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x60, 0x0a, 0x08, 0x53,
	0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x25, 0x2e, 0x69, 0x6f, 0x2e, 0x6d, 0x6f, 0x75,
	0x6c, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x6b, 0x69, 0x74, 0x5f, 0x6d, 0x6f, 0x64,
	0x75, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x2b,
	0x2e, 0x69, 0x6f, 0x2e, 0x6d, 0x6f, 0x75, 0x6c, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72,
	0x6b, 0x69, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2e,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x77, 0x0a,
	0x0a, 0x45, 0x63, 0x68, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x30, 0x2e, 0x69, 0x6f,
	0x2e, 0x6d, 0x6f, 0x75, 0x6c, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x6b, 0x69, 0x74,
	0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x45, 0x63, 0x68,
	0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x31, 0x2e,
	0x69, 0x6f, 0x2e, 0x6d, 0x6f, 0x75, 0x6c, 0x2e, 0x61, 0x64, 0x61, 0x70, 0x74, 0x65, 0x72, 0x6b,
	0x69, 0x74, 0x5f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x5f, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x45,
	0x63, 0x68, 0x6f, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x3b, 0x64, 0x65, 0x6d,
	0x6f, 0x6d, 0x6f, 0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_demomod_proto_rawDescOnce sync.Once
	file_demomod_proto_rawDescData = file_demomod_proto_rawDesc
)

func file_demomod_proto_rawDescGZIP() []byte {
	file_demomod_proto_rawDescOnce.Do(func() {
		file_demomod_proto_rawDescData = protoimpl.X.CompressGZIP(file_demomod_proto_rawDescData)
	})
	return file_demomod_proto_rawDescData
}

var file_demomod_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_demomod_proto_goTypes = []interface{}{
	(*Empty)(nil),             // 0: io.moul.adapterkit_module_demo.Empty
	(*Sum)(nil),               // 1: io.moul.adapterkit_module_demo.Sum
	(*HelloResult)(nil),       // 2: io.moul.adapterkit_module_demo.HelloResult
	(*EchoStream)(nil),        // 3: io.moul.adapterkit_module_demo.EchoStream
	(*Sum_Request)(nil),       // 4: io.moul.adapterkit_module_demo.Sum.Request
	(*Sum_Result)(nil),        // 5: io.moul.adapterkit_module_demo.Sum.Result
	(*EchoStream_Input)(nil),  // 6: io.moul.adapterkit_module_demo.EchoStream.Input
	(*EchoStream_Output)(nil), // 7: io.moul.adapterkit_module_demo.EchoStream.Output
}
var file_demomod_proto_depIdxs = []int32{
	4, // 0: io.moul.adapterkit_module_demo.DemomodSvc.Sum:input_type -> io.moul.adapterkit_module_demo.Sum.Request
	0, // 1: io.moul.adapterkit_module_demo.DemomodSvc.SayHello:input_type -> io.moul.adapterkit_module_demo.Empty
	6, // 2: io.moul.adapterkit_module_demo.DemomodSvc.EchoStream:input_type -> io.moul.adapterkit_module_demo.EchoStream.Input
	5, // 3: io.moul.adapterkit_module_demo.DemomodSvc.Sum:output_type -> io.moul.adapterkit_module_demo.Sum.Result
	2, // 4: io.moul.adapterkit_module_demo.DemomodSvc.SayHello:output_type -> io.moul.adapterkit_module_demo.HelloResult
	7, // 5: io.moul.adapterkit_module_demo.DemomodSvc.EchoStream:output_type -> io.moul.adapterkit_module_demo.EchoStream.Output
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_demomod_proto_init() }
func file_demomod_proto_init() {
	if File_demomod_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_demomod_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demomod_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demomod_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demomod_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoStream); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demomod_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sum_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demomod_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sum_Result); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demomod_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoStream_Input); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_demomod_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EchoStream_Output); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_demomod_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_demomod_proto_goTypes,
		DependencyIndexes: file_demomod_proto_depIdxs,
		MessageInfos:      file_demomod_proto_msgTypes,
	}.Build()
	File_demomod_proto = out.File
	file_demomod_proto_rawDesc = nil
	file_demomod_proto_goTypes = nil
	file_demomod_proto_depIdxs = nil
}
